# Generated by Django 4.0.2 on 2022-07-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.TextField(max_length=20)),
                ('empname', models.TextField(max_length=50)),
                ('empemail', models.TextField(max_length=50)),
                ('taskname', models.TextField(max_length=100)),
                ('duedate', models.TextField(max_length=20)),
                ('taskstatus', models.TextField(max_length=15)),
                ('tasksummary', models.TextField(max_length=500)),
            ],
        ),
    ]
